apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab-runner-vmi.fullname" . }}-config
  labels:
    {{- include "gitlab-runner-vmi.labels" . | nindent 4 }}
data:
  config.toml: |
    concurrent = 1
    check_interval = 0

    [[runners]]
      name = "{{ .Release.Name }}"
      url = "{{ .Values.runner.url }}"
      token = "{{ .Values.runner.token }}"
      executor = "{{ .Values.runner.executor }}"
      [runners.custom_build_dir]
      [runners.cache]
        [runners.cache.s3]
        [runners.cache.gcs]
        [runners.cache.azure]
      [runners.docker]
        tls_verify = false
        image = "{{ .Values.runner.dockerImage }}"
        privileged = false
        disable_entrypoint_overwrite = false
        oom_kill_disable = false
        disable_cache = false
        volumes = ["/cache"]
        shm_size = 0
