apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner-vmi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yonigofman/gitlab-vmi-provisioner.git
    targetRevision: HEAD
    path: helm/gitlab-runner-vmi
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
